### ISSUE TITLE
IF logic in function upload() fails

### ISSUE THREAD

**Issue by nomad64** [rodriguestiago0/actualbudget-backup#5]
It appears my ActualBudget backups broke some time ago. After looking at it for a bit, it seems to be tripping up on some `if` loop logic in `function upload()`, specifically, line 52:
```
        if !(file "${BACKUP_FILE_ZIP}" | grep -q "Zip archive data" ) ; then
            color red "Error downloading file"

            exit 1
        fi
```

If I comment out this code, the backup appears to run normally. Can you take a look to see what is going on?

Compose file (minus sensitive info):
```
version: "3.5"
services:
  actual_server:
    ...

  backups:
    image: rodriguestiago0/actualbudget-backup:latest
    environment:
      ACTUAL_BUDGET_URL: {{ app.actualbudget.actual_server_url_local }}
      ACTUAL_BUDGET_PASSWORD: ""
      ACTUAL_BUDGET_SYNC_ID: ""
      ACTUAL_BUDGET_SYNC_ID_1: ""
      RCLONE_REMOTE_NAME: LocalDir
      RCLONE_REMOTE_DIR: /ActualBudgetBackup
      BACKUP_FILE_SUFFIX: '%Y%m%d_%H%M%S'
      BACKUP_KEEP_DAYS: 14
      TIMEZONE: 'America/Chicago'
    volumes:
      - /mnt/docker/actualbudget/backup_config:/config/
      - /mnt/backup/Server_Backup_Files/ActualBudget:/ActualBudgetBackup
```

`rclone.conf` file:
```
[LocalDir]
type = local
```

Output of `backup.sh` when manually run inside container:
```
71823f53550a:~# /app/backup.sh
running the backup program at 2025-04-13 19:19:43 CDT
ACTUAL_BUDGET_URL: http://actualbudget:5006
ACTUAL_BUDGET_PASSWORD: *****
ACTUAL_BUDGET_SYNC_ID: 0199
ACTUAL_BUDGET_SYNC_ID: 708b
========================================
CRON: 0 0 * * *
RCLONE_REMOTE: LocalDir:/ActualBudgetBackup
RCLONE_GLOBAL_FLAG: 
BACKUP_FILE_DATE_FORMAT: %Y%m%d_%H%M%S (example "[filename].20250413_191943.zip")
BACKUP_KEEP_DAYS: 14
TIMEZONE: America/Chicago
========================================
Downloading Actual Budget backup
Login into Actual Budget
Get file id for 0199
Downloading backup files
Get file id for 708b
Downloading backup files
total 3M     
drwxr-xr-x    2 root     root        4.0K Apr 13 19:19 .
drwx------    1 root     root        4.0K Apr 13 19:19 ..
-rw-r--r--    1 root     root        2.7M Apr 13 19:19 backup.0199.20250413_191944.zip
-rw-r--r--    1 root     root       78.7K Apr 13 19:19 backup.708b.20250413_191944.zip
Error downloading file
```

**Comment by rodriguestiago0** [comment]
Mine is working correctly. 
Can you check if the latest files are correct?
Can you try recreating the pod?
Can you validate if the files are correctly generated in the end?

**Comment by rodriguestiago0** [comment]
Added some logs in the latest version. can you check again?

**Comment by nomad64** [comment]
I re-created and updated the container and ran `backup.sh` again, got the same failure. The output is below. Note: I have truncated the sync IDs from the output.

The backup files are created and downloaded successfully to `/root/backup` within the container.

```
ccc8e480eaeb:~# /app/backup.sh 
running the backup program at 2025-04-14 08:30:51 CDT
ACTUAL_BUDGET_URL: http://actualbudget:5006
ACTUAL_BUDGET_PASSWORD: *****
ACTUAL_BUDGET_SYNC_ID: 0199
ACTUAL_BUDGET_SYNC_ID: 708b
========================================
CRON: 0 0 * * *
RCLONE_REMOTE: LocalDir:/ActualBudgetBackup
RCLONE_GLOBAL_FLAG: 
BACKUP_FILE_DATE_FORMAT: %Y%m%d_%H%M%S (example "[filename].20250414_083051.zip")
BACKUP_KEEP_DAYS: 14
TIMEZONE: America/Chicago
========================================
Downloading Actual Budget backup
Login into Actual Budget
Get file id for 0199
file name "backup/backup.0199.20250414_083052.zip"
Downloading backup files
Get file id for 708b
file name "backup/backup.708b.20250414_083052.zip"
Downloading backup files
total 3M     
drwxr-xr-x    2 root     root        4.0K Apr 14 08:30 .
drwx------    1 root     root        4.0K Apr 14 08:30 ..
-rw-r--r--    1 root     root        2.7M Apr 14 08:30 backup.0199.20250414_083052.zip
-rw-r--r--    1 root     root       78.7K Apr 14 08:30 backup.708b.20250414_083052.zip
file name "backup/backup.0199.20250414_083052.zip"
file name "backup/backup.708b.20250414_083052.zip"
Error downloading file
```

Interestingly, if I run the `if` logic on a file directly, it passes just fine:
```
/data # cd ~/backup/
~/backup # ls -la
total 2848
drwxr-xr-x    2 root     root          4096 Apr 14 08:30 .
drwx------    1 root     root          4096 Apr 14 08:42 ..
-rw-r--r--    1 root     root       2822150 Apr 14 08:30 backup.0199.20250414_083052.zip
-rw-r--r--    1 root     root         80600 Apr 14 08:30 backup.708b.20250414_083052.zip
~/backup # if !(file backup.0199.20250414_083052.zip | grep -q "Zip archive data" ) ; then echo "pass";  fi
~/backup # 
```

**Comment by rodriguestiago0** [comment]
Can you try again? with the latest version?

thanks

**Comment by nomad64** [comment]
Still errors out, output below.

```
~ # /app/backup.sh 
running the backup program at 2025-04-14 12:54:29 CDT
ACTUAL_BUDGET_URL: http://actualbudget:5006
ACTUAL_BUDGET_PASSWORD: *****
ACTUAL_BUDGET_SYNC_ID: 0199
ACTUAL_BUDGET_SYNC_ID: 708b
========================================
CRON: 0 0 * * *
RCLONE_REMOTE: LocalDir:/ActualBudgetBackup
RCLONE_GLOBAL_FLAG: 
BACKUP_FILE_DATE_FORMAT: %Y%m%d_%H%M%S (example "[filename].20250414_125429.zip")
BACKUP_KEEP_DAYS: 14
TIMEZONE: America/Chicago
========================================
Downloading Actual Budget backup
Login into Actual Budget
Get file id for 0199
file name "backup/backup.0199.20250414_125429.zip"
Downloading backup files
Get file id for 708bd571-a266-4837-8f33-09f71da329c8
file name "backup/backup.708b.20250414_125429.zip"
Downloading backup files
total 3M     
drwxr-xr-x    2 root     root        4.0K Apr 14 12:54 .
drwx------    1 root     root        4.0K Apr 14 12:54 ..
-rw-r--r--    1 root     root        2.7M Apr 14 12:54 backup.0199.20250414_125429.zip
-rw-r--r--    1 root     root       78.7K Apr 14 12:54 backup.708b.20250414_125429.zip
file name "backup/backup.0199.20250414_125430.zip"
File not found "backup/backup.0199.20250414_125430.zip"
```

As with previous runs, the files are present in `/root/backup`
```
~/backup # pwd
/root/backup
~/backup # ls -la
total 2848
drwxr-xr-x    2 root     root          4096 Apr 14 12:59 .
drwx------    1 root     root          4096 Apr 14 12:54 ..
-rw-r--r--    1 root     root       2822150 Apr 14 12:54 backup.0199.20250414_125429.zip
-rw-r--r--    1 root     root         80600 Apr 14 12:54 backup.708b.20250414_125429.zip
```
As if we needed more confusion, it looks like the backup ran successfully last night at midnight per its normal schedule. 😕 

If it helps, I updated the first line of `backup.sh` to `#!/bin/bash -x` for the debugging output:
```
/data # /app/backup.sh 
+ . /app/includes.sh
++ ENV_FILE=/.env
++ CRON_CONFIG_FILE=/root/crontabs
+ cd /root
++ date '+%Y-%m-%d %H:%M:%S %Z'
+ color blue 'running the backup program at 2025-04-14 13:11:58 CDT'
+ case $1 in
+ echo -e '\033[34mrunning the backup program at 2025-04-14 13:11:58 CDT\033[0m'
running the backup program at 2025-04-14 13:11:58 CDT
+ init_env
+ export_env_file
+ [[ -f /.env ]]
+ get_env CRON
+ local VAR=CRON
+ local VAR_FILE=CRON_FILE
+ local VAR_DOTENV=DOTENV_CRON
+ local VAR_DOTENV_FILE=DOTENV_CRON_FILE
+ local VALUE=
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ export CRON=
+ CRON=
+ CRON='0 0 * * *'
+ get_env RCLONE_REMOTE_NAME
+ local VAR=RCLONE_REMOTE_NAME
+ local VAR_FILE=RCLONE_REMOTE_NAME_FILE
+ local VAR_DOTENV=DOTENV_RCLONE_REMOTE_NAME
+ local VAR_DOTENV_FILE=DOTENV_RCLONE_REMOTE_NAME_FILE
+ local VALUE=
+ [[ -n LocalDir ]]
+ VALUE=LocalDir
+ export RCLONE_REMOTE_NAME=LocalDir
+ RCLONE_REMOTE_NAME=LocalDir
+ RCLONE_REMOTE_NAME=LocalDir
+ RCLONE_REMOTE_NAME_0=LocalDir
+ get_env RCLONE_REMOTE_DIR
+ local VAR=RCLONE_REMOTE_DIR
+ local VAR_FILE=RCLONE_REMOTE_DIR_FILE
+ local VAR_DOTENV=DOTENV_RCLONE_REMOTE_DIR
+ local VAR_DOTENV_FILE=DOTENV_RCLONE_REMOTE_DIR_FILE
+ local VALUE=
+ [[ -n /ActualBudgetBackup ]]
+ VALUE=/ActualBudgetBackup
+ export RCLONE_REMOTE_DIR=/ActualBudgetBackup
+ RCLONE_REMOTE_DIR=/ActualBudgetBackup
+ RCLONE_REMOTE_DIR=/ActualBudgetBackup
+ RCLONE_REMOTE_DIR_0=/ActualBudgetBackup
+ get_rclone_remote_list
+ RCLONE_REMOTE_LIST=()
+ local i=0
+ local RCLONE_REMOTE_NAME_X_REFER
+ local RCLONE_REMOTE_DIR_X_REFER
+ local RCLONE_REMOTE_X
+ true
+ RCLONE_REMOTE_NAME_X_REFER=RCLONE_REMOTE_NAME_0
+ RCLONE_REMOTE_DIR_X_REFER=RCLONE_REMOTE_DIR_0
+ get_env RCLONE_REMOTE_NAME_0
+ local VAR=RCLONE_REMOTE_NAME_0
+ local VAR_FILE=RCLONE_REMOTE_NAME_0_FILE
+ local VAR_DOTENV=DOTENV_RCLONE_REMOTE_NAME_0
+ local VAR_DOTENV_FILE=DOTENV_RCLONE_REMOTE_NAME_0_FILE
+ local VALUE=
+ [[ -n LocalDir ]]
+ VALUE=LocalDir
+ export RCLONE_REMOTE_NAME_0=LocalDir
+ RCLONE_REMOTE_NAME_0=LocalDir
+ get_env RCLONE_REMOTE_DIR_0
+ local VAR=RCLONE_REMOTE_DIR_0
+ local VAR_FILE=RCLONE_REMOTE_DIR_0_FILE
+ local VAR_DOTENV=DOTENV_RCLONE_REMOTE_DIR_0
+ local VAR_DOTENV_FILE=DOTENV_RCLONE_REMOTE_DIR_0_FILE
+ local VALUE=
+ [[ -n /ActualBudgetBackup ]]
+ VALUE=/ActualBudgetBackup
+ export RCLONE_REMOTE_DIR_0=/ActualBudgetBackup
+ RCLONE_REMOTE_DIR_0=/ActualBudgetBackup
+ [[ -z LocalDir ]]
+ [[ -z /ActualBudgetBackup ]]
++ sed 's@\(/*\)$@@'
++ echo LocalDir:/ActualBudgetBackup
+ RCLONE_REMOTE_X=LocalDir:/ActualBudgetBackup
+ RCLONE_REMOTE_LIST=(${RCLONE_REMOTE_LIST[@]} "${RCLONE_REMOTE_X}")
+ (( i++ ))
+ true
+ RCLONE_REMOTE_NAME_X_REFER=RCLONE_REMOTE_NAME_1
+ RCLONE_REMOTE_DIR_X_REFER=RCLONE_REMOTE_DIR_1
+ get_env RCLONE_REMOTE_NAME_1
+ local VAR=RCLONE_REMOTE_NAME_1
+ local VAR_FILE=RCLONE_REMOTE_NAME_1_FILE
+ local VAR_DOTENV=DOTENV_RCLONE_REMOTE_NAME_1
+ local VAR_DOTENV_FILE=DOTENV_RCLONE_REMOTE_NAME_1_FILE
+ local VALUE=
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ export RCLONE_REMOTE_NAME_1=
+ RCLONE_REMOTE_NAME_1=
+ get_env RCLONE_REMOTE_DIR_1
+ local VAR=RCLONE_REMOTE_DIR_1
+ local VAR_FILE=RCLONE_REMOTE_DIR_1_FILE
+ local VAR_DOTENV=DOTENV_RCLONE_REMOTE_DIR_1
+ local VAR_DOTENV_FILE=DOTENV_RCLONE_REMOTE_DIR_1_FILE
+ local VALUE=
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ export RCLONE_REMOTE_DIR_1=
+ RCLONE_REMOTE_DIR_1=
+ [[ -z '' ]]
+ break
+ get_env RCLONE_GLOBAL_FLAG
+ local VAR=RCLONE_GLOBAL_FLAG
+ local VAR_FILE=RCLONE_GLOBAL_FLAG_FILE
+ local VAR_DOTENV=DOTENV_RCLONE_GLOBAL_FLAG
+ local VAR_DOTENV_FILE=DOTENV_RCLONE_GLOBAL_FLAG_FILE
+ local VALUE=
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ export RCLONE_GLOBAL_FLAG=
+ RCLONE_GLOBAL_FLAG=
+ RCLONE_GLOBAL_FLAG=
+ get_env BACKUP_KEEP_DAYS
+ local VAR=BACKUP_KEEP_DAYS
+ local VAR_FILE=BACKUP_KEEP_DAYS_FILE
+ local VAR_DOTENV=DOTENV_BACKUP_KEEP_DAYS
+ local VAR_DOTENV_FILE=DOTENV_BACKUP_KEEP_DAYS_FILE
+ local VALUE=
+ [[ -n 14 ]]
+ VALUE=14
+ export BACKUP_KEEP_DAYS=14
+ BACKUP_KEEP_DAYS=14
+ BACKUP_KEEP_DAYS=14
+ get_env BACKUP_FILE_SUFFIX
+ local VAR=BACKUP_FILE_SUFFIX
+ local VAR_FILE=BACKUP_FILE_SUFFIX_FILE
+ local VAR_DOTENV=DOTENV_BACKUP_FILE_SUFFIX
+ local VAR_DOTENV_FILE=DOTENV_BACKUP_FILE_SUFFIX_FILE
+ local VALUE=
+ [[ -n %Y%m%d_%H%M%S ]]
+ VALUE=%Y%m%d_%H%M%S
+ export BACKUP_FILE_SUFFIX=%Y%m%d_%H%M%S
+ BACKUP_FILE_SUFFIX=%Y%m%d_%H%M%S
+ get_env BACKUP_FILE_DATE
+ local VAR=BACKUP_FILE_DATE
+ local VAR_FILE=BACKUP_FILE_DATE_FILE
+ local VAR_DOTENV=DOTENV_BACKUP_FILE_DATE
+ local VAR_DOTENV_FILE=DOTENV_BACKUP_FILE_DATE_FILE
+ local VALUE=
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ export BACKUP_FILE_DATE=
+ BACKUP_FILE_DATE=
+ get_env BACKUP_FILE_DATE_SUFFIX
+ local VAR=BACKUP_FILE_DATE_SUFFIX
+ local VAR_FILE=BACKUP_FILE_DATE_SUFFIX_FILE
+ local VAR_DOTENV=DOTENV_BACKUP_FILE_DATE_SUFFIX
+ local VAR_DOTENV_FILE=DOTENV_BACKUP_FILE_DATE_SUFFIX_FILE
+ local VALUE=
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ export BACKUP_FILE_DATE_SUFFIX=
+ BACKUP_FILE_DATE_SUFFIX=
++ sed ++ echo %Y%m%d's/[^0-9a-zA-Z%_-]//g'

+ BACKUP_FILE_DATE=%Y%m%d
++ echo %Y%m%d_%H%M%S
++ sed 's/\///g'
+ BACKUP_FILE_DATE_FORMAT=%Y%m%d_%H%M%S
+ get_env TIMEZONE
+ local VAR=TIMEZONE
+ local VAR_FILE=TIMEZONE_FILE
+ local VAR_DOTENV=DOTENV_TIMEZONE
+ local VAR_DOTENV_FILE=DOTENV_TIMEZONE_FILE
+ local VALUE=
+ [[ -n America/Chicago ]]
+ VALUE=America/Chicago
+ export TIMEZONE=America/Chicago
+ TIMEZONE=America/Chicago
++ wc -l
++ ls /usr/share/zoneinfo/America/Chicago
+ local TIMEZONE_MATCHED_COUNT=1
+ [[ 1 -ne 1 ]]
+ init_actual_env
+ get_env ACTUAL_BUDGET_URL
+ local VAR=ACTUAL_BUDGET_URL
+ local VAR_FILE=ACTUAL_BUDGET_URL_FILE
+ local VAR_DOTENV=DOTENV_ACTUAL_BUDGET_URL
+ local VAR_DOTENV_FILE=DOTENV_ACTUAL_BUDGET_URL_FILE
+ local VALUE=
+ [[ -n http://actualbudget:5006 ]]
+ VALUE=http://actualbudget:5006
+ export ACTUAL_BUDGET_URL=http://actualbudget:5006
+ ACTUAL_BUDGET_URL=http://actualbudget:5006
+ ACTUAL_BUDGET_URL=http://actualbudget:5006
+ color yellow 'ACTUAL_BUDGET_URL: http://actualbudget:5006'
+ case $1 in
+ echo -e '\033[33mACTUAL_BUDGET_URL: http://actualbudget:5006\033[0m'
ACTUAL_BUDGET_URL: http://actualbudget:5006
+ get_env ACTUAL_BUDGET_PASSWORD
+ local VAR=ACTUAL_BUDGET_PASSWORD
+ local VAR_FILE=ACTUAL_BUDGET_PASSWORD_FILE
+ local VAR_DOTENV=DOTENV_ACTUAL_BUDGET_PASSWORD
+ local VAR_DOTENV_FILE=DOTENV_ACTUAL_BUDGET_PASSWORD_FILE
+ local VALUE=
+ [[ -n  ]]
+ VALUE=''
+ export 'ACTUAL_BUDGET_PASSWORD='
+ ACTUAL_BUDGET_PASSWORD=''
+ ACTUAL_BUDGET_PASSWORD=''
+ color yellow 'ACTUAL_BUDGET_PASSWORD: *****'
+ case $1 in
+ echo -e '\033[33mACTUAL_BUDGET_PASSWORD: *****\033[0m'
ACTUAL_BUDGET_PASSWORD: *****
+ get_env ACTUAL_BUDGET_SYNC_ID
+ local VAR=ACTUAL_BUDGET_SYNC_ID
+ local VAR_FILE=ACTUAL_BUDGET_SYNC_ID_FILE
+ local VAR_DOTENV=DOTENV_ACTUAL_BUDGET_SYNC_ID
+ local VAR_DOTENV_FILE=DOTENV_ACTUAL_BUDGET_SYNC_ID_FILE
+ local VALUE=
+ [[ -n 0199 ]]
+ VALUE=0199
+ export ACTUAL_BUDGET_SYNC_ID=0199
+ ACTUAL_BUDGET_SYNC_ID=0199
+ [[ -z 0199 ]]
+ ACTUAL_BUDGET_SYNC_ID_0=0199
+ init_actual_sync_list
+ ACTUAL_BUDGET_SYNC_ID_LIST=()
+ local i=0
+ local ACTUAL_BUDGET_SYNC_ID_X_REFER
+ true
+ ACTUAL_BUDGET_SYNC_ID_X_REFER=ACTUAL_BUDGET_SYNC_ID_0
+ get_env ACTUAL_BUDGET_SYNC_ID_0
+ local VAR=ACTUAL_BUDGET_SYNC_ID_0
+ local VAR_FILE=ACTUAL_BUDGET_SYNC_ID_0_FILE
+ local VAR_DOTENV=DOTENV_ACTUAL_BUDGET_SYNC_ID_0
+ local VAR_DOTENV_FILE=DOTENV_ACTUAL_BUDGET_SYNC_ID_0_FILE
+ local VALUE=
+ [[ -n 0199 ]]
+ VALUE=0199
+ export ACTUAL_BUDGET_SYNC_ID_0=0199
+ ACTUAL_BUDGET_SYNC_ID_0=0199
+ [[ -z 0199 ]]
+ ACTUAL_BUDGET_SYNC_ID_LIST=(${ACTUAL_BUDGET_SYNC_ID_LIST[@]} ${!ACTUAL_BUDGET_SYNC_ID_X_REFER})
+ (( i++ ))
+ true
+ ACTUAL_BUDGET_SYNC_ID_X_REFER=ACTUAL_BUDGET_SYNC_ID_1
+ get_env ACTUAL_BUDGET_SYNC_ID_1
+ local VAR=ACTUAL_BUDGET_SYNC_ID_1
+ local VAR_FILE=ACTUAL_BUDGET_SYNC_ID_1_FILE
+ local VAR_DOTENV=DOTENV_ACTUAL_BUDGET_SYNC_ID_1
+ local VAR_DOTENV_FILE=DOTENV_ACTUAL_BUDGET_SYNC_ID_1_FILE
+ local VALUE=
+ [[ -n 708b ]]
+ VALUE=708b
+ export ACTUAL_BUDGET_SYNC_ID_1=708b
+ ACTUAL_BUDGET_SYNC_ID_1=708b
+ [[ -z 708b ]]
+ ACTUAL_BUDGET_SYNC_ID_LIST=(${ACTUAL_BUDGET_SYNC_ID_LIST[@]} ${!ACTUAL_BUDGET_SYNC_ID_X_REFER})
+ (( i++ ))
+ true
+ ACTUAL_BUDGET_SYNC_ID_X_REFER=ACTUAL_BUDGET_SYNC_ID_2
+ get_env ACTUAL_BUDGET_SYNC_ID_2
+ local VAR=ACTUAL_BUDGET_SYNC_ID_2
+ local VAR_FILE=ACTUAL_BUDGET_SYNC_ID_2_FILE
+ local VAR_DOTENV=DOTENV_ACTUAL_BUDGET_SYNC_ID_2
+ local VAR_DOTENV_FILE=DOTENV_ACTUAL_BUDGET_SYNC_ID_2_FILE
+ local VALUE=
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ export ACTUAL_BUDGET_SYNC_ID_2=
+ ACTUAL_BUDGET_SYNC_ID_2=
+ [[ -z '' ]]
+ break
+ for ACTUAL_BUDGET_SYNC_ID_X in "${ACTUAL_BUDGET_SYNC_ID_LIST[@]}"
+ color yellow 'ACTUAL_BUDGET_SYNC_ID: 0199'
+ case $1 in
+ echo -e '\033[33mACTUAL_BUDGET_SYNC_ID: 0199\033[0m'
ACTUAL_BUDGET_SYNC_ID: 0199
+ for ACTUAL_BUDGET_SYNC_ID_X in "${ACTUAL_BUDGET_SYNC_ID_LIST[@]}"
+ color yellow 'ACTUAL_BUDGET_SYNC_ID: 708b'
+ case $1 in
+ echo -e '\033[33mACTUAL_BUDGET_SYNC_ID: 708b\033[0m'
ACTUAL_BUDGET_SYNC_ID: 708b
+ color yellow ========================================
+ case $1 in
+ echo -e '\033[33m========================================\033[0m'
========================================
+ color yellow 'CRON: 0 0 * * *'
+ case $1 in
+ echo -e '\033[33mCRON: 0 0 * * *\033[0m'
CRON: 0 0 * * *
+ for RCLONE_REMOTE_X in "${RCLONE_REMOTE_LIST[@]}"
+ color yellow 'RCLONE_REMOTE: LocalDir:/ActualBudgetBackup'
+ case $1 in
+ echo -e '\033[33mRCLONE_REMOTE: LocalDir:/ActualBudgetBackup\033[0m'
RCLONE_REMOTE: LocalDir:/ActualBudgetBackup
+ color yellow 'RCLONE_GLOBAL_FLAG: '
+ case $1 in
+ echo -e '\033[33mRCLONE_GLOBAL_FLAG: \033[0m'
RCLONE_GLOBAL_FLAG: 
++ date +%Y%m%d_%H%M%S
+ color yellow 'BACKUP_FILE_DATE_FORMAT: %Y%m%d_%H%M%S (example "[filename].20250414_131158.zip")'
+ case $1 in
+ echo -e '\033[33mBACKUP_FILE_DATE_FORMAT: %Y%m%d_%H%M%S (example "[filename].20250414_131158.zip")\033[0m'
BACKUP_FILE_DATE_FORMAT: %Y%m%d_%H%M%S (example "[filename].20250414_131158.zip")
+ color yellow 'BACKUP_KEEP_DAYS: 14'
+ case $1 in
+ echo -e '\033[33mBACKUP_KEEP_DAYS: 14\033[0m'
BACKUP_KEEP_DAYS: 14
+ color yellow 'TIMEZONE: America/Chicago'
+ case $1 in
+ echo -e '\033[33mTIMEZONE: America/Chicago\033[0m'
TIMEZONE: America/Chicago
+ color yellow ========================================
+ case $1 in
+ echo -e '\033[33m========================================\033[0m'
========================================
+ check_rclone_connection
+ rclone config show LocalDir
+ [[ 0 != 0 ]]
+ local HAS_ERROR=FALSE
+ for RCLONE_REMOTE_X in "${RCLONE_REMOTE_LIST[@]}"
+ rclone mkdir LocalDir:/ActualBudgetBackup
+ [[ 0 != 0 ]]
+ [[ FALSE == \T\R\U\E ]]
+ clear_dir
+ rm -rf backup
+ backup
+ mkdir -p backup
+ download_actual_budget
+ color blue 'Downloading Actual Budget backup'
+ case $1 in
+ echo -e '\033[34mDownloading Actual Budget backup\033[0m'
Downloading Actual Budget backup
+ color green 'Login into Actual Budget'
+ case $1 in
+ echo -e '\033[32mLogin into Actual Budget\033[0m'
Login into Actual Budget
+ prepare_login_json
+ jq -Rs 'split("\u0000") | . as $a 
                  | reduce range(0; 2) as $i 
                  ({}; . + {($a[2*$i]): ($a[2*$i + 1])})'
+ printf '%s\0%s\0' loginMethod password
+ printf '%s\0%s\0' password ''
++ curl -s --location http://actualbudget:5006/account/login --header 'Content-Type: application/json' --data @/tmp/login.json
++ jq --raw-output .data.token
+ local TOKEN=6d29
+ rm /tmp/login.json
+ for ACTUAL_BUDGET_SYNC_ID_X in "${ACTUAL_BUDGET_SYNC_ID_LIST[@]}"
+ color green 'Get file id for 0199'
+ case $1 in
+ echo -e '\033[32mGet file id for 0199\033[0m'
Get file id for 0199
+ backup_file_name 0199
++ date +%Y%m%d_%H%M%S
+ NOW=20250414_131158
+ BACKUP_FILE_ZIP=backup/backup.0199.20250414_131158.zip
+ color blue 'file name "backup/backup.0199.20250414_131158.zip"'
+ case $1 in
+ echo -e '\033[34mfile name "backup/backup.0199.20250414_131158.zip"\033[0m'
file name "backup/backup.0199.20250414_131158.zip"
++ jq --raw-output '.data[] | select( [ .groupId | match("0199") ] | any) | .fileId'
++ curl -s --location http://actualbudget:5006/sync/list-user-files --header 'X-ACTUAL-TOKEN: 6d29'
+ local FILE_ID=0e51e7c6-7c1c-4e2a-abe0-f19fca18ab94
+ color green 'Downloading backup files'
+ case $1 in
+ echo -e '\033[32mDownloading backup files\033[0m'
Downloading backup files
+ curl -s --location http://actualbudget:5006/sync/download-user-file --header 'X-ACTUAL-TOKEN: 6d29' --header 'X-ACTUAL-FILE-ID: 0e51e7c6-7c1c-4e2a-abe0-f19fca18ab94' --output backup/backup.0199.20250414_131158.zip
+ for ACTUAL_BUDGET_SYNC_ID_X in "${ACTUAL_BUDGET_SYNC_ID_LIST[@]}"
+ color green 'Get file id for 708b'
+ case $1 in
+ echo -e '\033[32mGet file id for 708b\033[0m'
Get file id for 708b
+ backup_file_name 708b
++ date +%Y%m%d_%H%M%S
+ NOW=20250414_131159
+ BACKUP_FILE_ZIP=backup/backup.708b.20250414_131159.zip
+ color blue 'file name "backup/backup.708b.20250414_131159.zip"'
+ case $1 in
+ echo -e '\033[34mfile name "backup/backup.708b.20250414_131159.zip"\033[0m'
file name "backup/backup.708b.20250414_131159.zip"
++ curl -s --location http://actualbudget:5006/sync/list-user-files --header 'X-ACTUAL-TOKEN: 6d29'
++ jq --raw-output '.data[] | select( [ .groupId | match("708b") ] | any) | .fileId'
+ local FILE_ID=ae5cbcee-33ad-4605-ac43-41b916e21949
+ color green 'Downloading backup files'
+ case $1 in
+ echo -e '\033[32mDownloading backup files\033[0m'
Downloading backup files
+ curl -s --location http://actualbudget:5006/sync/download-user-file --header 'X-ACTUAL-TOKEN: 6d29' --header 'X-ACTUAL-FILE-ID: ae5cbcee-33ad-4605-ac43-41b916e21949' --output backup/backup.708b.20250414_131159.zip
+ ls -lah backup
total 3M     
drwxr-xr-x    2 root     root        4.0K Apr 14 13:11 .
drwx------    1 root     root        4.0K Apr 14 13:11 ..
-rw-r--r--    1 root     root        2.7M Apr 14 13:11 backup.0199.20250414_131158.zip
-rw-r--r--    1 root     root       78.7K Apr 14 13:11 backup.708b.20250414_131159.zip
+ upload
+ for ACTUAL_BUDGET_SYNC_ID_X in "${ACTUAL_BUDGET_SYNC_ID_LIST[@]}"
+ backup_file_name 0199
++ date +%Y%m%d_%H%M%S
+ NOW=20250414_131159
+ BACKUP_FILE_ZIP=backup/backup.0199.20250414_131159.zip
+ color blue 'file name "backup/backup.0199.20250414_131159.zip"'
+ case $1 in
+ echo -e '\033[34mfile name "backup/backup.0199.20250414_131159.zip"\033[0m'
file name "backup/backup.0199.20250414_131159.zip"
+ file backup/backup.0199.20250414_131159.zip
+ grep -q 'Zip archive data'
+ color red 'File not found "backup/backup.0199.20250414_131159.zip"'
+ case $1 in
+ echo -e '\033[31mFile not found "backup/backup.0199.20250414_131159.zip"\033[0m'
File not found "backup/backup.0199.20250414_131159.zip"
+ exit 1
```

**Comment by rodriguestiago0** [comment]
Found the issue:
-rw-r--r--    1 root     root        2.7M Apr 14 12:54 backup.0199.20250414_125429.zip
-rw-r--r--    1 root     root       78.7K Apr 14 12:54 backup.708b.20250414_125429.zip
file name "backup/backup.0199.20250414_125430.zip"
File not found "backup/backup.0199.20250414_125430.zip"

The file name changes

**Comment by nomad64** [comment]
Those file names look the same to me?

Doing some digging, it looks like one of the ZIP files doesn't have the correct file type:
```
~/backup # file backup.708b.20250414_132854.zip 
backup.708b.20250414_132854.zip: data
```
Note that the first file completes the loop just fine, but the second file fails. Looking at the first file type, it appears correct:
```
~/backup # file backup.0199.20250414_132854.zip 
backup.0199.20250414_132854.zip: Zip archive data, at least v2.0 to extract, compression method=deflate
```

**Comment by rodriguestiago0** [comment]
fixed now

**Comment by rodriguestiago0** [comment]
Let me know if it solved your issue

**Comment by nomad64** [comment]
Looks like there are other issues with this latest update:
```
ffd82db6f22e:~# /app/backup.sh 
/app/backup.sh: line 99: color: command not found
/app/backup.sh: line 101: init_env: command not found
/app/backup.sh: line 105: check_rclone_connection: command not found
/app/backup.sh: line 22: color: command not found
/app/backup.sh: line 23: color: command not found
total 8K     
drwxr-xr-x    2 root     root        4.0K Apr 14 14:52 .
drwx------    1 root     root        4.0K Apr 14 14:52 ..
/app/backup.sh: line 112: color: command not found
```
Did you mean to comment out this line?
https://github.com/rodriguestiago0/actualbudget-backup/blob/382356f5e877d3faa64639c7a721cea3fdb6147b/scripts/backup.sh#L3

Uncommenting that line and running again shows this:
```
ffd82db6f22e:~# /app/backup.sh 
running the backup program at 2025-04-14 14:53:02 CDT
ACTUAL_BUDGET_URL: http://actualbudget:5006
ACTUAL_BUDGET_PASSWORD: *****
ACTUAL_BUDGET_SYNC_ID: 0199
ACTUAL_BUDGET_SYNC_ID: 708b
========================================
CRON: 0 0 * * *
RCLONE_REMOTE: LocalDir:/ActualBudgetBackup
RCLONE_GLOBAL_FLAG: 
BACKUP_FILE_DATE_FORMAT: %Y%m%d_%H%M%S (example "[filename].20250414_145302.zip")
BACKUP_KEEP_DAYS: 14
TIMEZONE: America/Chicago
========================================
Downloading Actual Budget backup
Login into Actual Budget
Get file id for 0199
file name "backup/backup.0199.20250414_145302.zip"
Downloading backup files
Get file id for 708b
file name "backup/backup.708b.20250414_145302.zip"
Downloading backup files
total 3M     
drwxr-xr-x    2 root     root        4.0K Apr 14 14:53 .
drwx------    1 root     root        4.0K Apr 14 14:53 ..
-rw-r--r--    1 root     root        2.7M Apr 14 14:53 backup.0199.20250414_145302.zip
-rw-r--r--    1 root     root       78.7K Apr 14 14:53 backup.708b.20250414_145302.zip
file name "backup/backup.0199.20250414_145302.zip"
file name "backup/backup.708b.20250414_145302.zip"
File not found "backup/backup.708b.20250414_145302.zip"
```

**Comment by rodriguestiago0** [comment]
fixed

**Comment by nomad64** [comment]
Still failing on that second file:
```
7deb5795243e:~# /app/backup.sh 
running the backup program at 2025-04-14 15:45:02 CDT
ACTUAL_BUDGET_URL: http://actualbudget:5006
ACTUAL_BUDGET_PASSWORD: *****
ACTUAL_BUDGET_SYNC_ID: 0199
ACTUAL_BUDGET_SYNC_ID: 708b
========================================
CRON: 0 0 * * *
RCLONE_REMOTE: LocalDir:/ActualBudgetBackup
RCLONE_GLOBAL_FLAG: 
BACKUP_FILE_DATE_FORMAT: %Y%m%d_%H%M%S (example "[filename].20250414_154502.zip")
BACKUP_KEEP_DAYS: 14
TIMEZONE: America/Chicago
========================================
Downloading Actual Budget backup
Login into Actual Budget
Get file id for 0199
file name "backup/backup.0199.20250414_154502.zip"
Downloading backup files
Get file id for 708b
file name "backup/backup.708b.20250414_154502.zip"
Downloading backup files
total 3M     
drwxr-xr-x    2 root     root        4.0K Apr 14 15:45 .
drwx------    1 root     root        4.0K Apr 14 15:45 ..
-rw-r--r--    1 root     root        2.7M Apr 14 15:45 backup.0199.20250414_154502.zip
-rw-r--r--    1 root     root       78.7K Apr 14 15:45 backup.708b.20250414_154502.zip
file name "backup/backup.0199.20250414_154502.zip"
file name "backup/backup.708b.20250414_154502.zip"
File not found "backup/backup.708b.20250414_154502.zip"
```
The second file is still showing up as the wrong type:
```
deb5795243e:~/backup# file backup.0199dc89-ae67-4f11-8c22-5519d2daec5f.20250414_154502.zip 
backup.0199dc89-ae67-4f11-8c22-5519d2daec5f.20250414_154502.zip: Zip archive data, at least v2.0 to extract, compression method=deflate
7deb5795243e:~/backup# file backup.708bd571-a266-4837-8f33-09f71da329c8.20250414_154502.zip 
backup.708bd571-a266-4837-8f33-09f71da329c8.20250414_154502.zip: data
```
It also fails to extract:
```
7deb5795243e:~/backup# unzip backup.708bd571-a266-4837-8f33-09f71da329c8.20250414_154502.zip
Archive:  backup.708bd571-a266-4837-8f33-09f71da329c8.20250414_154502.zip
unzip: short read
```
This will cause the check to fail as expected. Although I am not sure why Actual is presenting an invalid ZIP file.

**Comment by rodriguestiago0** [comment]
Can you validate that actual are exporting the file correctly.

**Comment by nomad64** [comment]
I went into Actual and opened the budget with the sync ID beginning `708b`. I was able to download the ZIP file via the "Export data" button. I was able to extract the file successfully.

However, I noticed the file sizes are different between what is in the container vs what I have on my desktop:
Container:
```
7deb5795243e:~/backup# ls -l backup.708b.20250414_154502.zip
-rw-r--r--    1 root     root         80600 Apr 14 15:45 backup.708b.20250414_154502.zip
```
user@pop-os:~/Downloads$ ls -l AB_708b_backup.zip 
-rw-rw-r-- 1 user user 146126 Apr 14 16:14 AB_708b_backup.zip
```
As a note, this budget has End to End encryption enabled on it, whereas the other budget does not.

**Comment by rodriguestiago0** [comment]
Please enable it only for the faulty file and see if it works

**Comment by rodriguestiago0** [comment]
I never test it with a file with encryption.
I need to validate it

**Comment by nomad64** [comment]
Re-created the container with only the bad sync ID, and it fails by itself:
```
c09086069589:~# /app/backup.sh 
running the backup program at 2025-04-14 16:46:04 CDT
ACTUAL_BUDGET_URL: http://actualbudget:5006
ACTUAL_BUDGET_PASSWORD: *****
ACTUAL_BUDGET_SYNC_ID: 708b
========================================
CRON: 0 0 * * *
RCLONE_REMOTE: LocalDir:/ActualBudgetBackup
RCLONE_GLOBAL_FLAG: 
BACKUP_FILE_DATE_FORMAT: %Y%m%d_%H%M%S (example "[filename].20250414_164604.zip")
BACKUP_KEEP_DAYS: 14
TIMEZONE: America/Chicago
========================================
Downloading Actual Budget backup
Login into Actual Budget
Get file id for 708b
file name "backup/backup.708b.20250414_164604.zip"
Downloading backup files
total 88K    
drwxr-xr-x    2 root     root        4.0K Apr 14 16:46 .
drwx------    1 root     root        4.0K Apr 14 16:46 ..
-rw-r--r--    1 root     root       78.7K Apr 14 16:46 backup.708b.20250414_164604.zip
file name "backup/backup.708b.20250414_164604.zip"
File not found "backup/backup.708b.20250414_164604.zip"
```
Maybe encryption isn't yet supported. 😆 

For now, I will exclude this budget file from the backup rotation.

**Comment by blarg3891** [comment]
I had similar issues with my encrypted budget file.  The problem is with the file check in the upload function.
run the script and look at the file type
file /app/backup/backup.xxxxxxxxxxxxxxxxxxxxxx.zip  -> this shows it as type "data" not zip archive

in backup.sh

 if !(file "${BACKUP_FILE_ZIP}" | grep -q "Zip archive data" ) ; then -> this checks for a zip archive so it fails.

I modified the script locally 
if [ ! -s "${BACKUP_FILE_ZIP}" ]; then -> this just checks if the file exists

Once i made this change everything worked, file downloaded, and rclone uploaded etc.

Can you modify your script then i think we should all be good.

**Comment by blarg3891** [comment]
> I had similar issues with my encrypted budget file. The problem is with the file check in the upload function. run the script and look at the file type file /app/backup/backup.xxxxxxxxxxxxxxxxxxxxxx.zip -> this shows it as type "data" not zip archive
> 
> in backup.sh
> 
> if !(file "${BACKUP_FILE_ZIP}" | grep -q "Zip archive data" ) ; then -> this checks for a zip archive so it fails.
> 
> I modified the script locally if [ ! -s "${BACKUP_FILE_ZIP}" ]; then -> this just checks if the file exists
> 
> Once i made this change everything worked, file downloaded, and rclone uploaded etc.
> 
> Can you modify your script then i think we should all be good.

I take it back.  While this does download the file, its not importable.  I suppose the file would have to be downloaded unencrypted somehow.

**Comment by mwidomski** [comment]
I can confirm that with E2E encryption on the zip file as currently retrieved from ActualBackup appears to be encrypted, most likely with the E2E key specified in ActualBackup.

The Export functionality within ActualBackup itself exports an unencrypted zip file even with E2E encryption enabled, and does not support importing the encrypted zip at this time anyway.

So the easiest fix for this would be to externally trigger the export function and use that zip. If that's not feasible, we could try having the user specify their E2E Key in a variable and decrypt the zip file before upload.
